# Generated by Django 3.0.2 on 2020-10-22 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(default=None, max_length=128, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Iso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isoname', models.CharField(default=None, max_length=128, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regionname', models.CharField(default=None, max_length=128, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statename', models.CharField(default=None, max_length=128, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=128, null=True)),
                ('description', models.CharField(default=None, max_length=128, null=True)),
                ('justification', models.CharField(default='NA', max_length=128, null=True)),
                ('year', models.CharField(default=None, max_length=128, null=True)),
                ('longitude', models.CharField(default=None, max_length=128, null=True)),
                ('latitude', models.CharField(default='0.0', max_length=128, null=True)),
                ('area_hectares', models.CharField(default='0.00', max_length=128, null=True)),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='unesco.Category')),
                ('iso', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='unesco.Iso')),
                ('region', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='unesco.Region')),
                ('states', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='unesco.States')),
            ],
        ),
    ]
