# Generated by Django 3.0.2 on 2020-12-09 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unesco', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='categoryname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='iso',
            old_name='isoname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='regionname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='states',
            old_name='statename',
            new_name='name',
        ),
    ]
