# Generated by Django 3.0.2 on 2021-02-19 17:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('compu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='purchase_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 2, 19, 17, 50, 13, 826997, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='computer',
            name='timestamp',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2021, 2, 19, 17, 50, 21, 651545, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
