# Generated by Django 3.0.2 on 2021-02-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compu', '0003_auto_20210219_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='Purchase Date (mm/dd/yyyy)'),
        ),
    ]
