# Generated by Django 3.0.2 on 2021-02-21 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compu', '0004_auto_20210219_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='IP_address',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='computer',
            name='MAC_address',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='computer',
            name='computer_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='computer',
            name='location',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='computer',
            name='users_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
