# Generated by Django 3.0.2 on 2021-02-22 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compu', '0005_auto_20210221_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='operating_system',
            field=models.CharField(blank=True, choices=[('Windows 10', 'Windows 10'), ('Windows 8', 'Windows 8'), ('Linux', 'Linux')], max_length=30, null=True),
        ),
    ]
