# Generated by Django 3.0.2 on 2021-02-22 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compu', '0006_computer_operating_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operating_System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operating_system', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='computer',
            name='operating_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compu.Operating_System'),
        ),
    ]
