# Generated by Django 3.0.2 on 2021-02-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compu', '0007_auto_20210222_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='operating_system',
        ),
        migrations.AddField(
            model_name='computer',
            name='operating_system',
            field=models.ManyToManyField(blank=True, null=True, to='compu.Operating_System'),
        ),
    ]
