# Generated by Django 3.0.2 on 2021-02-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compu', '0008_auto_20210222_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='operating_system',
            field=models.ManyToManyField(blank=True, to='compu.Operating_System'),
        ),
    ]
