# Generated by Django 3.0.2 on 2021-02-22 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compu', '0009_auto_20210222_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='operating_system',
        ),
        migrations.AddField(
            model_name='computer',
            name='operating_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compu.Operating_System'),
        ),
    ]
