# Generated by Django 3.0.2 on 2021-02-23 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compu', '0010_auto_20210222_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='export_to_CSV',
            field=models.BooleanField(default=False),
        ),
    ]
