# Generated by Django 3.0.2 on 2021-02-04 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adpet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_animal', models.CharField(choices=[('CT', 'Cat'), ('DG', 'Dog')], default='DG', max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='ad',
            name='breed',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
