# Generated by Django 3.0.2 on 2021-02-09 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adpet', '0002_auto_20210208_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='specie',
            field=models.CharField(choices=[('CT', 'Cat'), ('DG', 'Dog')], max_length=200),
        ),
    ]
