# Generated by Django 3.0.2 on 2021-02-12 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adpet', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='contact',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adpet.Contact'),
        ),
    ]
