# Generated by Django 3.0.2 on 2021-02-09 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adpet', '0003_auto_20210208_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female')], null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='seize',
            field=models.IntegerField(choices=[(0, 'Small'), (1, 'Medium'), (2, 'Big')], null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='sterilized',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='vaccinated',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No')], null=True),
        ),
    ]
